### ISSUE TITLE
Genre creating no longer works

### ISSUE THREAD

**Issue by Suhankin** [LMH01/MGT2_Mod_Tool#74] opened 2021-09-17 00:59 UTC
**Describe the bug**
Adding a new genre and starting a game will result in game crashing because of the update that completely changed how genre settings work.

**To Reproduce**
1. Add a new genre
2. Start a new game

**Desktop (please complete the following information):**
 - Version of MGT2 Mod Tool: v3.0.0-alpha-1
 - Version of MGT2: 2021.09.09A

**Comment by LMH01** [comment] 2021-09-17 14:02
Thanks for the report.

The problem is likely related to the initial backup files.
Could you please do the following and tell me if it works:

Start the alpha version and go into `Backup -> Create backup -> Create new initial backup` and follow the instructions that pop up. This will update the initial backup files and everything should work again.

I have also created a new fr (#75) that is already implemented and will be either released in v3.0.0-alpha-2 or in v3.0.0.

**Closed** 2021-09-17 14:36 UTC
Labels: question
